services:
  content-hive:
    build: 
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
    container_name: content-hive
    ports:
      - "6123:6123"
    volumes:
      - ./runtime-data:/config
    environment:
      - TZ=Asia/Shanghai
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PLUGINS_REPO_REF_TYPE=${PLUGINS_REPO_REF_TYPE}
      - PLUGINS_REPO_REF=${PLUGINS_REPO_REF}
      - MEDIA_TRANSFORM_MAX_WORKERS=2
    restart: unless-stopped
