services:
  content-hive:
    build: 
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
    container_name: content-hive
    ports:
      - "6123:6123"
    volumes:
      - ./runtime-data:/config
      - ../plugins:/config/plugins
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
