"""initial schema

Revision ID: 16a3a949e015
Revises:
Create Date: 2026-03-06 18:19:13.336876

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from contenthive.database.orm_models import AwareDatetime

# revision identifiers, used by Alembic.
revision: str = "16a3a949e015"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("IMAGE", "VIDEO", name="mediatype"), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("cover", sa.String(), nullable=True),
        sa.Column("media_path", sa.String(), nullable=True),
        sa.Column("cover_path", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "DOWNLOADING", "COMPLETED", "FAILED", name="mediastatus"),
            nullable=False,
        ),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_media_deleted_at"), "media", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_media_status"), "media", ["status"], unique=False)
    op.create_index(op.f("ix_media_updated_at"), "media", ["updated_at"], unique=False)
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_platforms_deleted_at"), "platforms", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_platforms_updated_at"), "platforms", ["updated_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INACTIVE", "ACTIVE", "DISABLED", name="userstatus"),
            nullable=False,
        ),
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", AwareDatetime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_id", "uid", name="uq_platform_uid"),
    )
    op.create_index(op.f("ix_authors_deleted_at"), "authors", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_authors_updated_at"), "authors", ["updated_at"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_profiles_deleted_at"), "profiles", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_profiles_updated_at"), "profiles", ["updated_at"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("token_jti", sa.String(), nullable=False),
        sa.Column("expires_at", AwareDatetime(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("last_accessed_at", AwareDatetime(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_jti"),
        sa.UniqueConstraint("user_id", "device_id", name="uq_user_device"),
    )
    op.create_index(op.f("ix_sessions_deleted_at"), "sessions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False)
    op.create_table(
        "user_platforms",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(["platform_id"], ["platforms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "platform_id"),
    )
    op.create_index(
        op.f("ix_user_platforms_deleted_at"),
        "user_platforms",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_platforms_updated_at"),
        "user_platforms",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "parse_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pid", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("post_time", sa.Integer(), nullable=True),
        sa.Column("parser", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_id", "pid", name="uq_platform_pid"),
    )
    op.create_index(
        op.f("ix_parse_results_deleted_at"),
        "parse_results",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parse_results_updated_at"),
        "parse_results",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "user_authors",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "author_id"),
    )
    op.create_index(op.f("ix_user_authors_deleted_at"), "user_authors", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_authors_updated_at"), "user_authors", ["updated_at"], unique=False)
    op.create_table(
        "main_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PARSE_CONTENT", "MEDIA_DOWNLOAD", "CONTENT_ANALYSIS", name="tasktype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "CANCELED",
                "COMPLETED",
                "FAILED",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("PRIMARY", "LINKED", "REUSED", name="taskrole"),
            nullable=True,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", AwareDatetime(), nullable=True),
        sa.Column("completed_at", AwareDatetime(), nullable=True),
        sa.Column("primary_task_id", sa.Integer(), nullable=True),
        sa.Column("parse_result_id", sa.Integer(), nullable=True),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(["parse_result_id"], ["parse_results.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["primary_task_id"], ["main_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_main_tasks_deleted_at"), "main_tasks", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_main_tasks_status"), "main_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_main_tasks_task_id"), "main_tasks", ["task_id"], unique=True)
    op.create_index(op.f("ix_main_tasks_type"), "main_tasks", ["type"], unique=False)
    op.create_index(op.f("ix_main_tasks_updated_at"), "main_tasks", ["updated_at"], unique=False)
    op.create_index(op.f("ix_main_tasks_url"), "main_tasks", ["url"], unique=False)
    op.create_index(op.f("ix_main_tasks_user_id"), "main_tasks", ["user_id"], unique=False)
    op.create_table(
        "parse_result_media",
        sa.Column("parse_result_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parse_result_id"], ["parse_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parse_result_id", "media_id"),
    )
    op.create_table(
        "user_parse_results",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parse_result_id", sa.Integer(), nullable=False),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(["parse_result_id"], ["parse_results.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "parse_result_id"),
    )
    op.create_index(
        op.f("ix_user_parse_results_deleted_at"),
        "user_parse_results",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_parse_results_updated_at"),
        "user_parse_results",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "sub_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sub_task_id", sa.String(), nullable=False),
        sa.Column("main_task_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PARSE_CONTENT", "MEDIA_DOWNLOAD", "CONTENT_ANALYSIS", name="tasktype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "CANCELED",
                "COMPLETED",
                "FAILED",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", AwareDatetime(), nullable=True),
        sa.Column("completed_at", AwareDatetime(), nullable=True),
        sa.Column("depends_on_id", sa.Integer(), nullable=True),
        sa.Column("created_at", AwareDatetime(), nullable=False),
        sa.Column("updated_at", AwareDatetime(), nullable=False),
        sa.Column("deleted_at", AwareDatetime(), nullable=True),
        sa.ForeignKeyConstraint(["depends_on_id"], ["sub_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["main_task_id"], ["main_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub_task_id"),
    )
    op.create_index(op.f("ix_sub_tasks_deleted_at"), "sub_tasks", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_sub_tasks_status"), "sub_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_sub_tasks_type"), "sub_tasks", ["type"], unique=False)
    op.create_index(op.f("ix_sub_tasks_updated_at"), "sub_tasks", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_tasks_updated_at"), table_name="sub_tasks")
    op.drop_index(op.f("ix_sub_tasks_type"), table_name="sub_tasks")
    op.drop_index(op.f("ix_sub_tasks_status"), table_name="sub_tasks")
    op.drop_index(op.f("ix_sub_tasks_deleted_at"), table_name="sub_tasks")
    op.drop_table("sub_tasks")
    op.drop_index(op.f("ix_user_parse_results_updated_at"), table_name="user_parse_results")
    op.drop_index(op.f("ix_user_parse_results_deleted_at"), table_name="user_parse_results")
    op.drop_table("user_parse_results")
    op.drop_table("parse_result_media")
    op.drop_index(op.f("ix_main_tasks_user_id"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_url"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_updated_at"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_type"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_task_id"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_status"), table_name="main_tasks")
    op.drop_index(op.f("ix_main_tasks_deleted_at"), table_name="main_tasks")
    op.drop_table("main_tasks")
    op.drop_index(op.f("ix_user_authors_updated_at"), table_name="user_authors")
    op.drop_index(op.f("ix_user_authors_deleted_at"), table_name="user_authors")
    op.drop_table("user_authors")
    op.drop_index(op.f("ix_parse_results_updated_at"), table_name="parse_results")
    op.drop_index(op.f("ix_parse_results_deleted_at"), table_name="parse_results")
    op.drop_table("parse_results")
    op.drop_index(op.f("ix_user_platforms_updated_at"), table_name="user_platforms")
    op.drop_index(op.f("ix_user_platforms_deleted_at"), table_name="user_platforms")
    op.drop_table("user_platforms")
    op.drop_index(op.f("ix_sessions_updated_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_deleted_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_profiles_updated_at"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_deleted_at"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_authors_updated_at"), table_name="authors")
    op.drop_index(op.f("ix_authors_deleted_at"), table_name="authors")
    op.drop_table("authors")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_platforms_updated_at"), table_name="platforms")
    op.drop_index(op.f("ix_platforms_deleted_at"), table_name="platforms")
    op.drop_table("platforms")
    op.drop_index(op.f("ix_media_updated_at"), table_name="media")
    op.drop_index(op.f("ix_media_status"), table_name="media")
    op.drop_index(op.f("ix_media_deleted_at"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
