"""The author added banner and description field.

Revision ID: 5d2da04c7dfd
Revises: b3e8c2d09f4a
Create Date: 2026-03-30 13:55:18.137788

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d2da04c7dfd"
down_revision: str | Sequence[str] | None = "b3e8c2d09f4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("banner", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("banner")

    # ### end Alembic commands ###
